name: A-Frame-Mazing-Architecture
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
    ports:
      - "1433:1433"
    volumes:
      - ~/Projects/sql-data:/var/opt/mssql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s